version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: faiss-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: faiss_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faiss-api-main
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    volumes:
      - ./Root_Folder:/app/Root_Folder
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mongodb://admin:123@mongodb:27017/faiss_db?authSource=admin
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:


networks:
  app-network:
    driver: bridge
