version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Root_Folder:/app/Root_Folder
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://admin:123@localhost:27017/faiss_db?authSource=admin
    networks:
      - app-network

volumes:
  mongo-data:


networks:
  app-network:
    driver: bridge
